#!/usr/bin/env node
// Everything derived from profile.json is generated here, so the README terminal (SVG),
// the README project list, the interactive terminal (index.html) and the link-preview
// image can never drift apart.
//
//   node scripts/generate.mjs             regenerate everything
//   node scripts/generate.mjs --no-fetch  skip the GitHub API (keeps the current repo snapshot)
//   node scripts/generate.mjs --no-og     skip og.png
//
// Outputs:
//   terminal.svg   README terminal, JetBrains Mono subsets from assets/fonts embedded
//   index.html     GEN:art / GEN:info / GEN:projects / GEN:repos blocks
//   README.md      GEN:projects block (`ls ~/projects` with real links)
//   og.png         link preview rendered from terminal.svg (qlmanage on macOS, else headless Chrome)
import { readFileSync, writeFileSync, existsSync, mkdtempSync, readdirSync, rmSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { tmpdir, homedir } from 'node:os';
import { fileURLToPath } from 'node:url';
import { execFileSync, spawnSync } from 'node:child_process';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const args = new Set(process.argv.slice(2));
const data = JSON.parse(readFileSync(join(root, 'profile.json'), 'utf8'));

const CH = 7.8;                       // JetBrains Mono advance @ 13px (0.6em)
const LH = 20;                        // art line height
const LEFT = 20;                      // terminal left margin
const ART_TOP = 116;                  // first art baseline
const INFO_X = LEFT + 63 * CH;        // info column (60 art cols + 3 gap)
const GREEN = '#01d68a';
const DIM = '#555555';
const TEXT = '#dddddd';
const LINK = '#60a5fa';
const PROMPT = '#7dd3fc';

const x = (v) => +v.toFixed(2);
const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
const today = new Date().toISOString().slice(0, 10);

const user = data.user;
const promptText = `${user}:~$`;      // 16 chars
const cmdX = x(LEFT + promptText.length * CH);

// ── embedded fonts (subsets built by scripts/fonts.sh) ──
function fontFace(file, weight) {
  const path = join(root, 'assets', 'fonts', file);
  if (!existsSync(path)) {
    console.warn(`warn: ${file} missing, the SVG will rely on the visitor's fonts (run scripts/fonts.sh)`);
    return '';
  }
  const b64 = readFileSync(path).toString('base64');
  return `    @font-face { font-family: 'JetBrains Mono'; font-style: normal; font-weight: ${weight}; src: url(data:font/woff2;base64,${b64}) format('woff2'); }`;
}
const fontCss = [
  fontFace('JetBrainsMono-Regular.subset.woff2', 400),
  fontFace('JetBrainsMono-Bold.subset.woff2', 700),
].filter(Boolean).join('\n');

// ── CTA animation constants ──
const cmd = ' ' + data.cta.command;   // leading space after the prompt
const cmdW = x(cmd.length * CH);
const CTA_Y = 496;
const OUT1_Y = 520;
const OUT2_Y = 542;

// ── fastfetch info column ──
function infoSvg(entry, y) {
  if (entry.title) {
    return `  <text class="mono" fill="${GREEN}" font-weight="bold" x="${INFO_X}" y="${y}">${esc(entry.title)}</text>`;
  }
  if (entry.sep) {
    return `  <text class="mono" fill="${DIM}" x="${INFO_X}" y="${y}">${'─'.repeat(22)}</text>`;
  }
  if (entry.blank) return '';
  const colonX = x(INFO_X + entry.label.length * CH);
  const valX = x(colonX + 2 * CH);
  const fill = entry.link ? LINK : TEXT;
  return [
    `  <text class="mono" fill="${GREEN}" font-weight="bold" x="${INFO_X}" y="${y}">${esc(entry.label)}</text>`,
    `  <text class="mono" fill="${DIM}" x="${colonX}" y="${y}">: </text>`,
    `  <text class="mono" fill="${fill}" x="${valX}" y="${y}">${esc(entry.value)}</text>`,
  ].join('\n');
}

const fetchRows = data.art.map((line, i) => {
  const y = ART_TOP + i * LH;
  const artRow = `  <text class="mono" fill="${GREEN}" x="${LEFT}" y="${y}" xml:space="preserve">${esc(line)}</text>`;
  const infoRow = infoSvg(data.info[i] || { blank: true }, y);
  return infoRow ? artRow + '\n' + infoRow : artRow;
}).join('\n');

const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="900" height="634" viewBox="0 0 900 634" fill="none">
  <!-- Generated by scripts/generate.mjs from profile.json — do not edit by hand -->
  <title>Jaider Velasco — Terminal CV · click to open the interactive terminal</title>
  <style>
${fontCss}
    .bg { fill: #000000; }
    .header { fill: #141414; }
    .tab-bg { fill: #1c1c1c; }
    .mono { font-family: 'JetBrains Mono', 'Cascadia Code', 'Fira Code', Menlo, Consolas, monospace; font-size: 13px; }
    .small { font-family: 'JetBrains Mono', 'Cascadia Code', 'Fira Code', Menlo, Consolas, monospace; font-size: 12px; }
    .dim { fill: #777777; }
    .icon { stroke: #999999; fill: none; stroke-width: 1.5; }
    .icon-bright { stroke: #ffffff; fill: none; stroke-width: 1.5; stroke-linecap: round; }
    @keyframes blink { 0%,100%{opacity:1} 50%{opacity:0} }
    .blink { animation: blink 1s step-end infinite; }
    .type-cover { animation: typecover 9s steps(${cmd.length}, end) infinite; }
    .type-cursor { animation: cursormove 9s steps(${cmd.length}, end) infinite, blink 1s step-end infinite; }
    .cursor-gate { animation: cursorgate 9s linear infinite; }
    .out1 { opacity: 0; animation: out1show 9s linear infinite; }
    .out2 { opacity: 0; animation: out2show 9s linear infinite; }
    @keyframes typecover { 0%, 8% { transform: translateX(0); } 26%, 100% { transform: translateX(${cmdW}px); } }
    @keyframes cursormove { 0%, 8% { transform: translateX(0); } 26%, 100% { transform: translateX(${cmdW}px); } }
    @keyframes cursorgate { 0%, 28.9% { opacity: 1; } 29%, 97% { opacity: 0; } 100% { opacity: 1; } }
    @keyframes out1show { 0%, 28.9% { opacity: 0; } 29%, 96% { opacity: 1; } 98.5%, 100% { opacity: 0; } }
    @keyframes out2show { 0%, 32.9% { opacity: 0; } 33%, 96% { opacity: 1; } 98.5%, 100% { opacity: 0; } }
    @media (prefers-reduced-motion: reduce) {
      .type-cover { animation: none; transform: translateX(${cmdW}px); }
      .type-cursor { animation: none; transform: translateX(${cmdW}px); }
      .cursor-gate { animation: none; opacity: 0; }
      .out1, .out2 { animation: none; opacity: 1; }
      .blink { animation: none; }
    }
  </style>

  <!-- Window background with border -->
  <rect class="bg" width="900" height="634" rx="12"/>
  <rect x="0.5" y="0.5" width="899" height="633" rx="12" stroke="#222222" fill="none"/>

  <!-- ═══ TITLE BAR ═══ -->
  <rect class="header" x="1" y="1" width="898" height="44" rx="12"/>
  <rect class="header" x="1" y="34" width="898" height="10"/>
  <line x1="1" y1="44" x2="899" y2="44" stroke="#1a1a1a" stroke-width="1"/>

  <!-- Sidebar toggle -->
  <g transform="translate(14, 14)">
    <rect x="0" y="0" width="16" height="16" rx="2.5" stroke="#999999" stroke-width="1.3" fill="none"/>
    <line x1="5.5" y1="0" x2="5.5" y2="16" stroke="#999999" stroke-width="1.3"/>
  </g>

  <!-- Tab -->
  <rect class="tab-bg" x="44" y="1" width="190" height="43"/>
  <line x1="234" y1="8" x2="234" y2="36" stroke="#2a2a2a" stroke-width="1"/>
  <g transform="translate(56, 14)">
    <rect x="0" y="1.5" width="14" height="13" rx="1.5" stroke="#999999" stroke-width="1.2" fill="none"/>
    <line x1="0" y1="5.5" x2="14" y2="5.5" stroke="#999999" stroke-width="1"/>
    <text x="7" y="13" text-anchor="middle" font-size="6" fill="#999999" stroke="none" font-family="monospace">_</text>
  </g>
  <text class="small" fill="#dddddd" x="80" y="26">${esc(user)}:~</text>

  <!-- + button -->
  <g transform="translate(245, 15)">
    <line x1="7" y1="2" x2="7" y2="12" stroke="#999999" stroke-width="1.8" stroke-linecap="round"/>
    <line x1="2" y1="7" x2="12" y2="7" stroke="#999999" stroke-width="1.8" stroke-linecap="round"/>
  </g>
  <g transform="translate(275, 15)">
    <polyline points="3,5 7,9 11,5" stroke="#999999" stroke-width="1.8" fill="none" stroke-linecap="round" stroke-linejoin="round"/>
  </g>

  <!-- Window controls -->
  <g transform="translate(780, 15)">
    <line x1="2" y1="7" x2="12" y2="7" class="icon-bright"/>
  </g>
  <g transform="translate(820, 15)">
    <rect x="2.5" y="2.5" width="9" height="9" rx="1.5" stroke="#ffffff" stroke-width="1.3" fill="none"/>
  </g>
  <g transform="translate(860, 15)">
    <line x1="3" y1="3" x2="11" y2="11" class="icon-bright"/>
    <line x1="11" y1="3" x2="3" y2="11" class="icon-bright"/>
  </g>

  <!-- ═══ FASTFETCH ═══ -->
  <text class="mono" fill="${PROMPT}" x="${LEFT}" y="80">${esc(promptText)}</text>
  <text class="mono" fill="${GREEN}" x="${cmdX}" y="80" xml:space="preserve"> ${esc(data.fetchCommand)}</text>
${fetchRows}

  <!-- ═══ ANIMATED CTA (plain terminal output, no chrome) ═══ -->
  <text class="mono" fill="${PROMPT}" x="${LEFT}" y="${CTA_Y}">${esc(promptText)}</text>
  <text class="mono" fill="${GREEN}" x="${cmdX}" y="${CTA_Y}" xml:space="preserve">${esc(cmd)}</text>
  <rect class="type-cover" x="${cmdX}" y="${CTA_Y - 15}" width="${x(cmdW + 4)}" height="20" fill="#000000"/>
  <g class="cursor-gate">
    <text class="mono type-cursor" fill="${GREEN}" x="${cmdX}" y="${CTA_Y}">█</text>
  </g>
  <text class="mono out1 dim" x="${LEFT}" y="${OUT1_Y}">${esc(data.cta.opening)}</text>
  <text class="mono out2" fill="${GREEN}" x="${LEFT}" y="${OUT2_Y}">${esc(data.cta.hint)}</text>

  <!-- ═══ BOTTOM BAR ═══ -->
  <line x1="1" y1="564" x2="899" y2="564" stroke="#1a1a1a" stroke-width="1"/>
  <rect fill="#000000" x="1" y="564" width="898" height="70"/>
  <rect fill="#000000" x="1" y="622" width="898" height="11" rx="12"/>

  <rect fill="#141414" x="14" y="572" width="56" height="24" rx="5" stroke="#2a2a2a" stroke-width="1"/>
  <g transform="translate(20, 577)">
    <path d="M1,2.5 C1,1.7 1.7,1 2.5,1 L5,1 L6.5,2.5 L11.5,2.5 C12.3,2.5 13,3.2 13,4 L13,10 C13,10.8 12.3,11.5 11.5,11.5 L2.5,11.5 C1.7,11.5 1,10.8 1,10 Z" stroke="#999999" stroke-width="1.1" fill="none"/>
  </g>
  <text class="small" fill="#bbbbbb" x="38" y="588">~</text>

  <text class="mono" fill="${GREEN}" font-weight="bold" opacity="0.7" x="16" y="616">$</text>
  <text class="mono blink" fill="${GREEN}" x="30" y="616">█</text>

</svg>
`;

writeFileSync(join(root, 'terminal.svg'), svg);
console.log(`terminal.svg regenerated (${(svg.length / 1024).toFixed(0)} KB, fonts ${fontCss ? 'embedded' : 'NOT embedded'})`);

// ── GitHub repos snapshot ──
async function fetchRepos() {
  let token = process.env.GITHUB_TOKEN;
  if (!token) {
    try { token = execFileSync('gh', ['auth', 'token'], { stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim(); } catch {}
  }
  const headers = { Accept: 'application/vnd.github+json', 'User-Agent': `${data.login}/generate.mjs` };
  if (token) headers.Authorization = 'Bearer ' + token;
  const res = await fetch(`https://api.github.com/users/${data.login}/repos?per_page=100&type=owner&sort=pushed`, { headers });
  if (!res.ok) throw new Error(`GitHub API ${res.status}`);
  const all = await res.json();
  return all
    .filter((r) => !r.fork && !r.archived)
    .map((r) => ({
      name: r.name,
      description: (r.description || '').replace(/\s+/g, ' ').trim(),
      stars: r.stargazers_count,
      lang: r.language || '',
      pushed: r.pushed_at.slice(0, 10),
      url: r.html_url,
      homepage: r.homepage || '',
    }));
}

let repos = null;
if (!args.has('--no-fetch')) {
  try {
    repos = await fetchRepos();
    console.log(`repos: ${repos.length} public repositories fetched`);
  } catch (e) {
    console.warn(`warn: could not fetch repos (${e.message}); keeping the current snapshot in index.html`);
  }
}

// ── patch index.html between GEN markers ──
const htmlPath = join(root, 'index.html');
let html = readFileSync(htmlPath, 'utf8');

const q = (s) => `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
const artJs = '    const art = [\n' + data.art.map((l) => `      ${q(l)},`).join('\n') + '\n    ];';
const infoJs = '    const info = [\n' + data.info.map((e) => {
  if (e.title) return `      { label: ${q(e.title)}, value: '', bold: true },`;
  if (e.sep) return `      { label: ${q('─'.repeat(22))}, value: '', sep: true },`;
  if (e.blank) return `      { label: '', value: '' },`;
  const link = e.link ? ', link: true' : '';
  return `      { label: ${q(e.label)}, value: ${q(e.value)}${link} },`;
}).join('\n') + '\n    ];';
const indentJson = (v, pad) => JSON.stringify(v, null, 2).split('\n').map((l, i) => (i ? pad + l : l)).join('\n');
const projectsJs = `const PROJECTS = ${indentJson(data.projects, '')};`;
const reposJs = repos
  ? `const REPOS_AT = '${today}';\nconst REPOS = ${indentJson(repos, '')};`
  : null;

const patch = (marker, block) => {
  const re = new RegExp(`(// GEN:${marker}[^\\n]*\\n)[\\s\\S]*?(\\n\\s*// GEN:${marker}:end)`);
  if (!re.test(html)) throw new Error(`marker GEN:${marker} not found in index.html`);
  html = html.replace(re, () => `$1${block}$2`.replace('$1', RegExp.$1).replace('$2', RegExp.$2));
};
// (String.replace with a function avoids `$` in base64/JSON being read as a back-reference.)
const patchFn = (marker, block) => {
  const re = new RegExp(`(// GEN:${marker}[^\\n]*\\n)[\\s\\S]*?(\\n\\s*// GEN:${marker}:end)`);
  if (!re.test(html)) throw new Error(`marker GEN:${marker} not found in index.html`);
  html = html.replace(re, (_m, open, close) => open + block + close);
};
patchFn('art', artJs);
patchFn('info', infoJs);
patchFn('projects', projectsJs);
if (reposJs) patchFn('repos', reposJs);

// ── README: `ls ~/projects` with real links (SVG links are dead behind GitHub's camo proxy) ──
const readmePath = join(root, 'README.md');
let readme = readFileSync(readmePath, 'utf8');
const nameW = Math.max(...data.projects.map((p) => p.name.length + 1)) + 2;
const langW = Math.max(...data.projects.map((p) => p.lang.length)) + 2;
const lsRows = data.projects.map((p) => {
  const url = `https://github.com/${p.repo}`;
  const name = `<a href="${url}">${esc(p.name)}/</a>` + ' '.repeat(nameW - p.name.length - 1);
  const lang = esc(p.lang).padEnd(langW);
  const withNote = p.with ? ` · with <a href="https://github.com/${p.with}">@${esc(p.with)}</a>` : '';
  return name + lang + esc(p.tagline) + withNote;
});
const lsBlock = [
  '<pre>',
  `${esc(promptText)} ls ~/projects`,
  ...lsRows,
  '</pre>',
].join('\n');
const readmeRe = /(<!-- GEN:projects[^\n]*-->\n)[\s\S]*?(\n<!-- GEN:projects:end -->)/;
if (!readmeRe.test(readme)) throw new Error('marker GEN:projects not found in README.md');
readme = readme.replace(readmeRe, (_m, open, close) => open + lsBlock + close);
writeFileSync(readmePath, readme);

// ── og.png: link preview rendered from the SVG ──
function pngSize(buf) {
  return { width: buf.readUInt32BE(16), height: buf.readUInt32BE(20) };
}
function findChrome() {
  if (process.env.CHROME) return { bin: process.env.CHROME, shell: /headless[-_]shell/i.test(process.env.CHROME) };
  // Playwright's chrome-headless-shell renders the SVG in ~2 s; full Chrome's new headless mode can take minutes on macOS.
  const cache = join(homedir(), 'Library', 'Caches', 'ms-playwright');
  if (existsSync(cache)) {
    const dirs = readdirSync(cache).filter((d) => d.startsWith('chromium_headless_shell-')).sort().reverse();
    for (const d of dirs) {
      const bin = join(cache, d, `chrome-headless-shell-mac-${process.arch === 'arm64' ? 'arm64' : 'x64'}`, 'chrome-headless-shell');
      if (existsSync(bin)) return { bin, shell: true };
    }
  }
  const chrome = [
    '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
    '/usr/bin/google-chrome', '/usr/bin/chromium', '/usr/bin/chromium-browser',
  ].find(existsSync);
  return chrome ? { bin: chrome, shell: false } : null;
}
function renderOg() {
  const svgPath = join(root, 'terminal.svg');
  const out = join(root, 'og.png');
  const tmp = mkdtempSync(join(tmpdir(), 'gh-jaider-og-'));
  try {
    const chrome = findChrome();
    if (chrome) {
      const r = spawnSync(chrome.bin, [
        chrome.shell ? '--headless' : '--headless=new', '--disable-gpu', '--hide-scrollbars', '--no-first-run', '--no-default-browser-check',
        `--user-data-dir=${join(tmp, 'profile')}`, '--window-size=900,634', '--force-device-scale-factor=2',
        '--virtual-time-budget=2500', `--screenshot=${out}`, 'file://' + svgPath,
      ], { stdio: 'ignore', timeout: chrome.shell ? 60000 : 180000 });
      if (r.status === 0 && existsSync(out)) return chrome.shell ? 'chrome-headless-shell' : 'chrome';
    }
    // macOS QuickLook is instant but pads the thumbnail to a square, so crop it back to the SVG's aspect.
    if (process.platform === 'darwin') {
      const r = spawnSync('qlmanage', ['-t', '-s', '1800', '-o', tmp, svgPath], { stdio: 'ignore', timeout: 60000 });
      const produced = join(tmp, 'terminal.svg.png');
      if (r.status === 0 && existsSync(produced)) {
        const { width } = pngSize(readFileSync(produced));
        const height = Math.round((width * 634) / 900);
        spawnSync('sips', ['-c', String(height), String(width), '--cropOffset', '0', '0', produced, '--out', out], { stdio: 'ignore', timeout: 60000 });
        if (existsSync(out)) return 'qlmanage';
      }
    }
  } finally {
    rmSync(tmp, { recursive: true, force: true });
  }
  return null;
}
if (!args.has('--no-og')) {
  const how = renderOg();
  if (how) {
    const { width, height } = pngSize(readFileSync(join(root, 'og.png')));
    html = html
      .replace(/(property="og:image:width" content=")[^"]*/, `$1${width}`)
      .replace(/(property="og:image:height" content=")[^"]*/, `$1${height}`);
    console.log(`og.png rendered with ${how} (${width}×${height})`);
  } else {
    console.warn('warn: og.png not rendered (no qlmanage or Chrome available); the previous one is kept');
  }
}

writeFileSync(htmlPath, html);
console.log(`index.html patched (art, info, projects${reposJs ? ', repos' : ''}), README.md patched (projects)`);
